### ISSUE TITLE
map OSID agent id to actual name

### ISSUE THREAD

**Issue by luwen-huang** [wombats-writing-code/fbw-instructor#18]
I think you already have a function somewhere but I can't find it. can just import it in and call it to get us pretty names?:

https://github.com/wombats-writing-code/fbw-instructor/blob/master/web/src/routes/Dashboard/components/QuestionResult/QuestionResult.js#L4

**Comment by cjshawMIT** [comment]
I think this exists partly in the instructor app and partly in platform-common, so I’ll have to move the instructor part over (it’s in the recommendation / results selectors)

**Comment by cjshawMIT** [comment]
I think this exists partly in the instructor app and partly in platform-common, so I’ll have to move the instructor part over (it’s in the recommendation / results selectors)

**Comment by luwen-huang** [comment]
i think i've standardized this in `platform-common/selectors/login/index.js`
