### ISSUE TITLE
one single bankId for each user

### ISSUE THREAD

**Issue by luwen-huang** [wombats-writing-code/fbw-instructor#19]
It's super confusing between term bank Ids and private bank ids and other bank ids. Every user (whether instructor or student) should make calls to the middleman using their privateBankId (because we think it'll improve perf), and the middleman should calculate it. 

code changes needed to middleman, both apps, and platform common. pending bug fixes also dependent on this.

**Comment by cjshawMIT** [comment]
I think this should be "make calls to the middleman using the termBankId and the middleman calculates the privateBankId"

**Comment by cjshawMIT** [comment]
I've pushed some fixes to platform-common, middleman and student app to complement the middleman updates from yesterday. I've deployed student and instructor -- it all seems to work as before and is standardized on using the termBankId in the apps / tests. Please verify.
