### ISSUE TITLE
deleting a mission results in 500

### ISSUE THREAD

**Issue by luwen-huang** [wombats-writing-code/fbw-instructor#20]
Try deleting the Quiz UI Test mission on the Instructor app. It's returning a 500. 

Might be dependent on #19  because it could be using a wrong bankId.

**Comment by luwen-huang** [comment]
actually, deleting other missions work. I wonder if it's an issue on the middleman side with deleting missions that have takens.

**Comment by cjshawMIT** [comment]
Yeah, you need to send in the `termBankId` (otherwise the middleman can't find all the takens to delete them). I tested it out and will redeploy the instructor app with updated `platform-common`.
