### ISSUE TITLE
instructors want 11:59pm as time for deadline

### ISSUE THREAD

**Issue by luwen-huang** [wombats-writing-code/fbw-instructor#22]
whenever an end date is selected, e.g. Friday Mar 11, the app should automatically set the time to 11:59pm of that day.

**Comment by cjshawMIT** [comment]
It should already do that — but times are UTC times, so the time in the JSON won’t match your local time…do you have an example of when this isn’t true?

**Comment by luwen-huang** [comment]
It's not a bug I noticed per se, just a request by the faculty that 11:59pm
be their local (Denver) time.

Luwen

**Comment by cjshawMIT** [comment]
Ah, that makes sense, so that is an issue we have to resolve then…somewhere in platform-common selectors I think...
