### ISSUE TITLE
editMission reducer not initialized on -dev

### ISSUE THREAD

**Issue by cjshawMIT** [wombats-writing-code/fbw-instructor#24]
@luwen-huang : wondering if you can replicate?

Running on localhost, if I just go to `/login`, I can check that the `editMission` reducer initialized properly with `spawnDate` as an object with `startDate` and `deadline`.

On -dev, when I go to `/login`, `editMission` reducer is empty -- did not initialize. This makes the default `startDate` and `deadline` null for launching phase 2...which needs to have a default.

The code when I tried it should have been identical. I was running `npm start` in one window and ran `npm run s3:dev` which compiled and deployed the exact same code to -dev.

**Comment by luwen-huang** [comment]
ok, i've tweaked the `createStore` state slicer. try building and seeing if it works now?

**Comment by cjshawMIT** [comment]
Reopening because it seems the `editMission` is getting serialized as a string, but it needs to be passed to the datePicker as a moment object.

![captura de pantalla 2017-01-18 a las 11 38 56 am](https://cloud.githubusercontent.com/assets/4930129/22073202/b69b701e-dd72-11e6-90f8-365e7ef4343e.png)

**Comment by cjshawMIT** [comment]
fixed with updated `createStore.js`
