### ISSUE TITLE
editMission backend part is not properly saving missions

### ISSUE THREAD

**Issue by luwen-huang** [wombats-writing-code/fbw-instructor#36]
the frontend UI luckily caught this error. It's saving all of your 'test edit missions' with a default genus type: 

![simulator screen shot jan 28 2017 5 24 05 pm](https://cloud.githubusercontent.com/assets/2822290/22395636/bc06c9a4-e57e-11e6-9e6e-4c2b6526d372.png)
![simulator screen shot jan 28 2017 5 23 52 pm](https://cloud.githubusercontent.com/assets/2822290/22395638/bcfd5666-e57e-11e6-9292-000163d1925a.png)

**Comment by cjshawMIT** [comment]
Hm, thanks, then this is really an error with the test in platform-common, because it should be deleting them...

**Comment by cjshawMIT** [comment]
RE-running the platform-common edit-mission test shows that it does delete the mission now so I think these were cruft. I've re-copied the data from prod, so the cruft is gone from dev (which is the only place I saw the Test Edit missions).
