### ISSUE TITLE
Bank "items" not re-gotten when switching between domains

### ISSUE THREAD

**Issue by cjshawMIT** [wombats-writing-code/fbw-instructor#37]
When using LuwenHuang, and you switch from MAT121 to ACC121, the items don't get reloaded. I think this is non-urgent since it should only be us who have this issue for now...

![captura de pantalla 2017-01-30 a las 9 23 57 am](https://cloud.githubusercontent.com/assets/4930129/22426722/5971e066-e6ce-11e6-8b53-aeb989627ea0.png)

**Comment by luwen-huang** [comment]
not relevant anymore...
