### ISSUE TITLE
Datepicker CSS getting cut off?

### ISSUE THREAD

**Issue by cjshawMIT** [wombats-writing-code/fbw-instructor#38]
OS X Sierra, Chrome 55, our test D2L login:

![captura de pantalla 2017-01-30 a las 2 26 00 pm](https://cloud.githubusercontent.com/assets/4930129/22437957/21b20d48-e6f8-11e6-8c5e-5f9b202b4414.png)

**Comment by luwen-huang** [comment]
not using datepicker anymore, current datetime selector works fine and doesn't have issues (i think)
