### ISSUE TITLE
Phase II / grades for student with 100% in phase I

### ISSUE THREAD

**Issue by cjshawMIT** [wombats-writing-code/fbw-instructor#49]
Shows up as `NaN`

<img width="76" alt="captura de pantalla 2017-02-16 a las 3 54 44 pm" src="https://cloud.githubusercontent.com/assets/4930129/23040704/4583ed0c-f460-11e6-8bdc-389589e42290.png">

This is because the student got a 100% on phase 1, and then got a taken with 0 sections for phase 2 (which got calculated at `NaN`). Arguably this is two bugs:

1) The student's grade should show 100%, not `NaN`.
2) The student probably should have never gotten a phase 2.

<img width="167" alt="captura de pantalla 2017-02-16 a las 3 57 06 pm" src="https://cloud.githubusercontent.com/assets/4930129/23040775/97096256-f460-11e6-9afd-f7854797275a.png">

<img width="171" alt="captura de pantalla 2017-02-16 a las 3 57 00 pm" src="https://cloud.githubusercontent.com/assets/4930129/23040781/9b823204-f460-11e6-8e23-7e0077029ec4.png">

**Comment by luwen-huang** [comment]
fixed and deployed
